# Generated by Django 3.2.8 on 2021-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mentors',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
