# Generated by Django 3.2.8 on 2021-10-21 05:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20211018_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='technical_board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('linkedin', models.URLField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='Interest',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=10000, size=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=10000, size=None),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=10000, size=None),
        ),
    ]
