# Generated by Django 3.2.8 on 2021-10-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211021_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='period',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
