# Generated by Django 3.2 on 2022-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_employee_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
