# Generated by Django 3.2 on 2022-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_employee_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
