# Generated by Django 3.2.8 on 2021-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20211024_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
