# Generated by Django 3.2 on 2022-01-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
