# Generated by Django 3.2.8 on 2021-10-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_employee_period'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project',
            new_name='project_teams',
        ),
    ]
