# Generated by Django 3.2.8 on 2021-10-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
