# Generated by Django 4.0 on 2021-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_teams',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
