# Generated by Django 3.2 on 2022-01-17 16:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_teams_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_teams',
            name='extra_members',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), blank=True, max_length=10000, null=True, size=None),
        ),
    ]
