# Generated by Django 3.2 on 2022-01-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_mentors_title'),
        ('project', '0008_project_teams_extra_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_teams',
            name='teamMembers',
            field=models.ManyToManyField(blank=True, null=True, to='team.employee'),
        ),
    ]
