# Generated by Django 3.2.8 on 2021-10-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talks',
            name='image',
        ),
        migrations.AddField(
            model_name='talks',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
